apiVersion: v2
name: base
version: 0.3.1
kubeVersion: ">= 1.21.0-0"
description: base chart
maintainers:
  - name: Igor Beliakov
    email: Igor.Beliakov@shell.com
    url: "https://github.com/weisdd"
