{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
{{- with .Values.pdb.minAvailable }}
  minAvailable: {{ . }}
{{- end }}
{{- with .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
{{- end }}
{{- end }}
