{{- if or .Values.serviceAccount.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "base.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "base.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "base.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{ if or .Values.serviceAccount.clusterRole.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.serviceAccount.clusterRole.bindWithClusterRoleBinding | ternary "Cluster" "" }}RoleBinding
metadata:
  name: {{ printf "%s%s%s" (.Values.serviceAccount.clusterRole.bindWithClusterRoleBinding | ternary (printf "%s-" .Release.Namespace) "") (include "base.fullname" .) "-cr" }}
  {{- if not .Values.serviceAccount.clusterRole.bindWithClusterRoleBinding }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ include "base.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "base.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
