{{- if .Values.serviceAccount.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "base.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
rules:
  {{- if .Values.serviceAccount.role.rules }}
  {{- toYaml .Values.serviceAccount.role.rules | nindent 2 }}
  {{- end -}}
{{- end }}
{{ if .Values.serviceAccount.clusterRole.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
rules:
  {{- if .Values.serviceAccount.clusterRole.rules }}
  {{- toYaml .Values.serviceAccount.clusterRole.rules | nindent 2 }}
  {{- end -}}
{{- end }}
