{{- if .Values.keyvault.secrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    keyvault/name: {{ .Values.keyvault.name }}
spec:
  provider: azure
  {{- if .Values.keyvault.exportAsEnv }}
  secretObjects:
    - secretName: {{ include "base.fullname" . }}-kv
      type: Opaque
      labels:
        keyvault/name: {{ .Values.keyvault.name }}
      data:
      {{- range $alias, $name := .Values.keyvault.secrets }}
        - key: {{ $alias }}
          objectName: {{ $alias }}
      {{- end }}
  {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyvault.clientID }}
    keyvaultName: {{ .Values.keyvault.name }}
    objects:  |
      array:
      {{- range $alias, $name := .Values.keyvault.secrets }}
        - |
          objectName: {{ $name }}
          objectAlias: {{ $alias }}
          objectType: secret
      {{- end }}
    tenantId: {{ .Values.keyvault.tenantID }}
{{- end }}
