{{- $root := . -}}
{{- range $containerName, $containerValues := .Values.containers }}
{{- if $containerValues.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "base.fullname" $root }}-{{ $containerName }}-secret-env
  labels:
    {{- include "base.labels" $root | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $containerValues.secretEnv }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
