{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "base.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
{{- end -}}
