apiVersion: v1
kind: Service
metadata:
  name: {{ template "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ports:
    {{- range $port_name, $port_values := .Values.service.ports }}
    - name: {{ $port_values.alias | default $port_name }}
      port: {{ $port_values.port }}
      protocol: TCP
      targetPort: {{ $port_values.targetPort }}
    {{- end }}
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
{{- $root := . -}}
{{- if eq .Values.type "StatefulSet" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "base.fullname" . }}-headless
  labels:
    {{- include "base.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    {{- range $port_name, $port_values := .Values.service.ports }}
    - name: {{ $port_name }}
      port: {{ $port_values.port }}
      protocol: TCP
      targetPort: {{ $port_values.targetPort }}
    {{- end }}
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  clusterIP: None
{{- end }}
