linters:
  enable:
    - gocritic
    - gosec
    - gofmt
    - goimports
    - gocyclo
    - goconst
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - unparam
    - errname
    - errchkjson
